name: Android CI

on:
  pull_request:
    types: [ "opened" ]
  push:
    branches-ignore:
      - "master"
jobs:
  build:
    name: Build Signed APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Here we need to decode keystore.jks from base64 string and place it
      # in the folder specified in the release signing configuration
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'ru.unilms.jks'
          fileDir: '/home/runner/work/application/application/app/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      # Build and sign APK ("-x test" argument is used to skip tests)
      - name: Build APK
        run: ./gradlew :app:assembleRelease -x test
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Retrieve Version
        run: |
          echo "::set-output name=VERSION_NAME::$(./gradlew -q printVersionName)"
        id: android_version

      # Show information about the APK's signing certificates
      - name: Verify Signature
        run: $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner verify --print-certs app/build/outputs/apk/release/UNI_${{steps.android_version.outputs.VERSION_NAME}}.apk

      # Save the APK after the Build job is complete to publish it as a Github release in the next job
      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: UNI
          path: app/build/outputs/apk/release/UNI_${{steps.android_version.outputs.VERSION_NAME}}.apk
  attach:
    permissions:
      contents: write
      pull-requests: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: UNI
      - name: Pull request artifacts
        uses: gavv/pull-request-artifacts@v1.0.0
        with:
          commit: $GITHUB_SHA
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            UNI/UNI_${{steps.android_version.outputs.VERSION_NAME}}.apk
